/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as Import } from './routes/_'
import { Route as SplatImport } from './routes/$'
import { Route as CvIndexImport } from './routes/cv/index'
import { Route as R1IndexImport } from './routes/1/index'
import { Route as TempSplatImport } from './routes/temp/$'
import { Route as Bos04Import } from './routes/bos/04'
import { Route as Articles1Import } from './routes/_.articles/1'

// Create/Update Routes

const Route = Import.update({
  id: '/_',
  getParentRoute: () => rootRoute,
} as any)

const SplatRoute = SplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRoute,
} as any)

const CvIndexRoute = CvIndexImport.update({
  id: '/cv/',
  path: '/cv/',
  getParentRoute: () => rootRoute,
} as any)

const R1IndexRoute = R1IndexImport.update({
  id: '/1/',
  path: '/1/',
  getParentRoute: () => rootRoute,
} as any)

const TempSplatRoute = TempSplatImport.update({
  id: '/temp/$',
  path: '/temp/$',
  getParentRoute: () => rootRoute,
} as any)

const Bos04Route = Bos04Import.update({
  id: '/bos/04',
  path: '/bos/04',
  getParentRoute: () => rootRoute,
} as any)

const Articles1Route = Articles1Import.update({
  id: '/articles/1',
  path: '/articles/1',
  getParentRoute: () => Route,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatImport
      parentRoute: typeof rootRoute
    }
    '/_': {
      id: '/_'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Import
      parentRoute: typeof rootRoute
    }
    '/bos/04': {
      id: '/bos/04'
      path: '/bos/04'
      fullPath: '/bos/04'
      preLoaderRoute: typeof Bos04Import
      parentRoute: typeof rootRoute
    }
    '/temp/$': {
      id: '/temp/$'
      path: '/temp/$'
      fullPath: '/temp/$'
      preLoaderRoute: typeof TempSplatImport
      parentRoute: typeof rootRoute
    }
    '/1/': {
      id: '/1/'
      path: '/1'
      fullPath: '/1'
      preLoaderRoute: typeof R1IndexImport
      parentRoute: typeof rootRoute
    }
    '/cv/': {
      id: '/cv/'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvIndexImport
      parentRoute: typeof rootRoute
    }
    '/_/articles/1': {
      id: '/_/articles/1'
      path: '/articles/1'
      fullPath: '/articles/1'
      preLoaderRoute: typeof Articles1Import
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface RouteChildren {
  Articles1Route: typeof Articles1Route
}

const RouteChildren: RouteChildren = {
  Articles1Route: Articles1Route,
}

const RouteWithChildren = Route._addFileChildren(RouteChildren)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '': typeof RouteWithChildren
  '/bos/04': typeof Bos04Route
  '/temp/$': typeof TempSplatRoute
  '/1': typeof R1IndexRoute
  '/cv': typeof CvIndexRoute
  '/articles/1': typeof Articles1Route
}

export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '': typeof RouteWithChildren
  '/bos/04': typeof Bos04Route
  '/temp/$': typeof TempSplatRoute
  '/1': typeof R1IndexRoute
  '/cv': typeof CvIndexRoute
  '/articles/1': typeof Articles1Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/$': typeof SplatRoute
  '/_': typeof RouteWithChildren
  '/bos/04': typeof Bos04Route
  '/temp/$': typeof TempSplatRoute
  '/1/': typeof R1IndexRoute
  '/cv/': typeof CvIndexRoute
  '/_/articles/1': typeof Articles1Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '' | '/bos/04' | '/temp/$' | '/1' | '/cv' | '/articles/1'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '' | '/bos/04' | '/temp/$' | '/1' | '/cv' | '/articles/1'
  id:
    | '__root__'
    | '/$'
    | '/_'
    | '/bos/04'
    | '/temp/$'
    | '/1/'
    | '/cv/'
    | '/_/articles/1'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  Route: typeof RouteWithChildren
  Bos04Route: typeof Bos04Route
  TempSplatRoute: typeof TempSplatRoute
  R1IndexRoute: typeof R1IndexRoute
  CvIndexRoute: typeof CvIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  Route: RouteWithChildren,
  Bos04Route: Bos04Route,
  TempSplatRoute: TempSplatRoute,
  R1IndexRoute: R1IndexRoute,
  CvIndexRoute: CvIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/$",
        "/_",
        "/bos/04",
        "/temp/$",
        "/1/",
        "/cv/"
      ]
    },
    "/$": {
      "filePath": "$.tsx"
    },
    "/_": {
      "filePath": "_.tsx",
      "children": [
        "/_/articles/1"
      ]
    },
    "/bos/04": {
      "filePath": "bos/04.tsx"
    },
    "/temp/$": {
      "filePath": "temp/$.tsx"
    },
    "/1/": {
      "filePath": "1/index.tsx"
    },
    "/cv/": {
      "filePath": "cv/index.tsx"
    },
    "/_/articles/1": {
      "filePath": "_.articles/1.tsx",
      "parent": "/_"
    }
  }
}
ROUTE_MANIFEST_END */
